stages:

  - name: build-and-publish
    jobs:

      - name: build-and-publish
        steps:

          - name: typescript-build
            type: AgnosticShellScript@0
            parameters:
              script:
                - npm install
                - tsc -b
          
          - name: docker-build
            type: AgnosticShellScript@0
            parameters:
              script:
                - docker build -t wsrelay:latest . --platform linux/arm64/v8

          - name: docker-login
            type: AgnosticShellScript@0
            parameters:
              script:
                - docker login containers

          - name: docker-tag
            type: AgnosticShellScript@0
            parameters:
              script:
                - docker tag wsrelay:latest containers:443/wsrelay:latest

          - name: docker-push
            type: AgnosticShellScript@0
            parameters:
              script:
                - docker push containers:443/wsrelay:latest

  - name: deploy
    jobs:

      - name: deploy-production
        steps:

          - name: docker-pull
            type: AgnosticShellScript@0
            parameters:
              script:
                - docker -H containers pull containers:443/wsrelay:latest

          - name: docker-replace
            type: AgnosticShellScript@0
            parameters:
              script:
                - docker -H containers stop wsrelay
                - docker -H containers rm wsrelay
                - docker -H containers run -d -p 22002:22002 --restart=always --name wsrelay containers:443/wsrelay:latest
